### ISSUE TITLE
Check Rac1.py

### ISSUE THREAD

**Issue by emibcn** [joan-domingo/Podcasts-RAC1-Android#2]
Hello there!
I've just updated my project [Rac1.py](https://github.com/emibcn/Rac1.py), a command-line script to listen to Rac1 catalan radio station using [new Rac1 external API](https://upcommons.upc.edu/bitstream/handle/2117/102378/121547.pdf?sequence=1&isAllowed=y).

I thought you'd like to hear of it, just as I liked to discover yours. Algo, I wanted to write this recommendation with a PM, but Github lacks of it.

Note: You can close or delete this issue, if you want.

Regards!
emi

**Comment by joan-domingo** [comment]
Hi Emi, thank you for your message !

I'm always happy to get to know new open source projects, especially if they are related. And I appreciate very much the API documentation you shared.

I'll have a look at the documentation and your project and I'll see if I can add new useful features to the android app.

And of course, I'll also mention your project. Let me know if I can be of any help.

Best,
Joan

**Comment by emibcn** [comment]
Helllo again,
I'm considering making a Kyvi app (PC & Android & iOS Python based app) with similar functionality to the ones of my Rac1.py app (and another app similar to that one for 1O-RM). If you know other parts of the public Rac1 REST API more than those I've wrote on Rac1.py, I'll appreciate any reference to it. If you'd like to contribute to some of those apps, just tell me and we can talk about it.

Best regards!!
emi

**Comment by joan-domingo** [comment]
These are the endpoints that I know or I'm using (from the RAC1 app):

* http://www.rac1.cat/audioteca/api/app/v1/schedule
* http://www.rac1.cat/audioteca/api/app/v1/now
* http://www.rac1.cat/audioteca/api/app/v1/programs
* http://www.rac1.cat/audioteca/api/app/v1/sessions/{programId}
* http://www.rac1.cat/audioteca/api/app/v1/sessions/{programId}/{sectionId}

I tried adding parameters to these endpoints, so I can get a bigger list of podcasts, but I wasn't successful. 

I'm not so interested in learning python, sorry :(

Best,
Joan

**Comment by emibcn** [comment]
Hello again!
I've just made another [Rac1 application, based on ReactJS](https://github.com/emibcn/Rac1.js) and [published using GitHub Pages](https://emibcn.github.io/Rac1.js). Thought you'd like to hear of it (again!).

Best regards!
emi

**Comment by joan-domingo** [comment]
Hi @emibcn , nice to hear from you! I've just added a link to the React app in the readme. 
It's good to see you building new stuff!
Best,
Joan
